version: "3.9"
services:
  client:
    build: ./client
    command: ["npm", "start"]
    ports: 
      - 3000:3000
    depends_on:
      - server
  server:
    build: ./server
    command: ["node", "index.js"]
    ports:
      - 8000:8000